version: '3.8'

services:
  test_runner:
    image: wordpress:cli
    container_name: wp-cli-tester
    volumes:
      - ./wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    networks:
      - wordpress-network
    command: /bin/bash -c "wp core install --url=http://localhost:8000 --title='My WordPress Site' --admin_user=admin --admin_password=password --admin_email=admin@example.com && wp core is-installed && echo 'WordPress is installed and accessible'"
