version: '3.8'

services:
  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test-runner
    container_name: wp-cli-tester
    volumes:
      - ./wordpress_data:/var/www/html
      - ./run_tests.py:/usr/local/bin/run_tests.py
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    networks:
      - wordpress-network
    command: python /usr/local/bin/run_tests.py

  fastapi_tester:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-tester
    networks:
      - wordpress-network
    volumes:
      - ./test_fastapi.py:/app/test_fastapi.py
